# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-18 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(max_length=50)),
                ('inuse', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TopicExtractionJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('reference', models.CharField(max_length=250)),
                ('processed', models.BooleanField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('perplexity', models.FloatField(blank=True, default=None, null=True)),
                ('decomposition', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('features_extraction', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('inuse', models.BooleanField()),
                ('fitted_model', models.BinaryField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('word', models.CharField(max_length=50)),
                ('inuse', models.BooleanField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic_modeler.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='topicextractionjob',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic_modeler.TopicModel'),
        ),
        migrations.AddField(
            model_name='topic',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic_modeler.TopicModel'),
        ),
    ]
