# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-18 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('perplexity', models.FloatField()),
                ('decomposition', models.CharField(max_length=250)),
                ('features_extraction', models.CharField(max_length=250)),
                ('fitted_model', models.BinaryField()),
            ],
        ),
    ]
